sudo: enabled
language: node_js
node_js:
  - 10.16.3
env:
  - COVERAGE=1
  - GAS=1
before_script:
    - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
script:
  - if [ "$COVERAGE" = "1" ]; then npm run coverage && bash <(curl -s https://codecov.io/bash); fi
  - if [ "$GAS" = "1" ]; then npm run test:gas-ci && npx codechecks; fi
