# Wait until a connection is established with http://localhost:8545
steps:
  - run: sleep 5
  - run:
      shell: /bin/sh
      command: |
        wget --retry-connrefused --waitretry=1 --read-timeout=600 --timeout=600 -t 1000 http://localhost:8545
        :
