jobs:
  - job-prepare:
      {{> filter-master.yml}}
  # ~~~~~~~~~~~~ Etherscan validation on MAINNET ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-mainnet
      network: mainnet
      {{> filter-master.yml}}
      {{> require-prepare.yml}}
  # ~~~~~~~~~~~~ Etherscan validation on RINKEBY ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-rinkeby
      network: rinkeby
      {{> filter-master.yml}}
      {{> require-prepare.yml}}
  # ~~~~~~~~~~~~ Etherscan validation on KOVAN ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-kovan
      network: kovan
      {{> filter-master.yml}}
      {{> require-prepare.yml}}
  # ~~~~~~~~~~~~ Etherscan validation on ROPSTEN ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-ropsten
      network: ropsten
      {{> filter-master.yml}}
      {{> require-prepare.yml}}
