triggers:
  - schedule:
      cron: "0 0 * * *"
      filters:
        branches:
          only:
            - master
jobs:
  - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Deployment validation
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-validate-deployments:
      {{> require-prepare.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-prod-tests:
      name: job-prod-tests-mainnet
      {{> require-prepare.yml}}
  - job-diff-prod-tests:
      name: job-diff-prod-tests-mainnet
      {{> require-prepare.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Local production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-diff-prod-tests-local:
      name: job-diff-prod-tests-local
      {{> require-prepare.yml}}
  - job-diff-prod-tests-local-ovm:
      name: job-diff-prod-tests-local-ovm
      {{> require-prepare.yml}}
