jobs:
  - job-prepare
  - job-unit-tests:
      {{> require-prepare.yml}}
  - job-unit-tests-coverage:
      {{> require-prepare.yml}}
  - job-unit-tests-gas-report:
      {{> require-prepare.yml}}
  - job-test-deploy-script:
      {{> require-prepare.yml}}
  - job-unit-tests-ovm:
      {{> require-prepare.yml}}
