# Starts optimism-integration L1 and L2 local chains and runs Optimism integration tests against them
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: git clone git@github.com:ethereum-optimism/optimism-integration.git
  - run: cd optimism-integration
  - run: docker-compose pull
  - run: ./up.sh
  - run: cd ..
  - run: node publish deploy-ovm-pair
  - run: npm run test:prod:ovm
