# Starts optimism-integration L1 and L2 local chains and runs Optimism integration tests against them
{{> job-header-machine.yml}}
resource_class: large
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Prepare docker
      command: |
        git clone git@github.com:ethereum-optimism/optimism-integration.git
        cd optimism-integration
        ls -la
        docker-compose pull
  - run:
      name: Start chains
      background: true
      command: |
        cd optimism-integration
        ./up.sh
  - run:
      shell: /bin/sh
      command: |
        wget --retry-connrefused --waitretry=1 --read-timeout=120 --timeout=120 -t 100 http://localhost:8545
        :
  - run:
      shell: /bin/sh
      command: |
        wget --retry-connrefused --waitretry=1 --read-timeout=120 --timeout=120 -t 100 http://localhost:9545
        :
  - run:
      name: Deploy Synthetix instances and run production tests
      command: |
        node publish deploy-ovm-pair
        npm run test:prod:ovm
