# Starts a forked chain, and runs the deploy command against it
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-fork-start:
      network: << parameters.network >>
      reset: true
  - run: node publish deploy --use-fork --yes --network << parameters.network >>
  - persist_to_workspace:
      root: .
      paths:
        - publish/deployed
        - .db
