# Restarts a forked chain, and runs production tests with gas reports against it
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      command: npx hardhat node --target-network mainnet
      background: true
  - cmd-wait-for-rpc
  - run: |
        which codechecks || true
        ls /home/root/.npm-global/bin || true
        ls /home/root/.config/yarn/global/node_modules/.bin || true
        ls /home/root/.yarn/bin || true
  - run: npm run test:prod:gas -- --target-network mainnet && DEBUG=* npx codechecks codechecks.prod.yml
  - store_artifacts:
      path: test-gas-used-prod.log
