# Simulates a deployment in a fork, and runs production tests against it
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  # Compile
  - run: node publish build
  # Start fork
  - run: npx hardhat node --target-network mainnet
  - cmd-wait-for-rpc
  # Prepare deploy
  - run: node publish prepare-deploy --network mainnet
  # Deploy
  - run: node publish deploy --add-new-synths --use-fork --yes --network mainnet
  # Run production tests
  - run: npm run test:prod:gas -- --patch-fresh-deployment && npx codechecks codechecks.prod.yml
  - store_artifacts:
      path: test-gas-used-prod.log
