working_directory: ~/repo
docker:
  - image: circleci/node:12.18
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npx buidler compile --optimizer --fail-oversize
  - run: npx buidler compile --ovm --optimizer --fail-oversize
