# Restarts a forked chain, and runs production tests with gas reports against it
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-fork-start
  - run: npm run test:prod:gas && npx codechecks codechecks.prod.yml
  - store_artifacts:
      path: test-gas-used-prod.log
